const itemGroup = [
    {
        id: 1,
        image: require('../images/1.jpg'),
        nameItem: 'Café 100% Colombiano',
        description: 'Café de grano entero, tostado oscuro y molido',
        price: 35000,
        discount: 20,
        category: 'Bebidas',
        ProductFeaturesItem: 'Café de origen colombiano, cultivado en la región cafetera. Sabor intenso y aroma cautivador. Ideal para preparar espresso, americano o cualquier bebida a base de café.',
        paymentMethods: ['Efectivo', 'Tarjeta de crédito', 'Transferencia bancaria'],
    },
    {
        id: 2,
        image: require('../images/2.jpg'),
        nameItem: 'Arroz Blanco Grano Largo',
        description: 'Arroz de alta calidad',
        price: 18500,
        discount: 5,
        category: 'Alimentos',
        ProductFeaturesItem: 'Arroz blanco de grano largo, ideal para acompañar tus platos favoritos. Cocción rápida y textura suave. Fuente de energía natural.',
        paymentMethods: ['Efectivo', 'Tarjeta de crédito'],
    },
    {
        id: 3,
        image: require('../images/3.jpg'),
        nameItem: 'Audífonos Inalámbricos',
        description: 'Sonido de alta fidelidad',
        price: 129900,
        category: 'Electrónica',
        ProductFeaturesItem: 'Audífonos inalámbricos con cancelación activa de ruido. Sonido envolvente y bajos profundos. Batería de larga duración. Perfectos para escuchar música y realizar llamadas.',
        paymentMethods: ['Efectivo', 'Tarjeta de crédito', 'PayPal'],
    },
    {
        id: 4,
        image: require('../images/4.jpg'),
        nameItem: 'Televisor Smart 4K',
        description: 'Experiencia visual superior',
        price: 1599900,
        discount: 35,
        category: 'Electrónica',
        ProductFeaturesItem: 'Televisor de 55 pulgadas con resolución 4K Ultra HD. Smart TV con acceso a tus aplicaciones favoritas y asistente de voz integrado. Disfruta de colores vibrantes y un contraste excepcional.',
        paymentMethods: ['Efectivo', 'Tarjeta de crédito', 'Transferencia bancaria', 'PayPal'],
    },
    {
        id: 5,
        image: require('../images/5.jpg'),
        nameItem: 'Mouse Inalámbrico Ergonómico',
        description: 'Comodidad y precisión',
        price: 99900,
        discount: 30,
        category: 'Electrónica',
        ProductFeaturesItem: 'Mouse inalámbrico con diseño ergonómico para reducir la fatiga en la mano. Conexión Bluetooth y sensor de alta precisión. Ideal para trabajar y jugar.',
        paymentMethods: ['Efectivo', 'Tarjeta de crédito'],
    },
    {
        id: 6,
        image: require('../images/6.jpg'),
        nameItem: 'Laptop Gamer',
        description: 'Potencia y rendimiento',
        price: 3299900,
        discount: 60,
        category: 'Electrónica',
        ProductFeaturesItem: 'Laptop gaming con procesador de última generación, tarjeta gráfica dedicada y pantalla de alta frecuencia de actualización. Disfruta de tus juegos favoritos con gráficos fluidos y sin retrasos.',
        paymentMethods: ['Efectivo', 'Tarjeta de crédito', 'Transferencia bancaria', 'PayPal'],
    },
    {
        id: 7,
        image: require('../images/7.jpg'),
        nameItem: 'Silla de Oficina Ergonómica',
        description: 'Comodidad y soporte',
        price: 899900,
        discount: 20,
        category: 'Muebles',
        ProductFeaturesItem: 'Silla de oficina ajustable en altura y respaldo, con reposabrazos acolchados. Diseñada para brindar comodidad y soporte durante largas jornadas de trabajo.',
        paymentMethods: ['Efectivo', 'Transferencia bancaria'],
    },
    {
        id: 8,
        image: require('../images/8.jpg'),
        nameItem: 'Escritorio de Madera',
        description: 'Elegante y funcional',
        price: 699900,
        category: 'Muebles',
        ProductFeaturesItem: 'Escritorio de madera maciza con amplio espacio de trabajo. Diseño moderno y minimalista. Perfecto para cualquier espacio de trabajo.',
        paymentMethods: ['Efectivo', 'Tarjeta de crédito'],
    }
];

export default itemGroup;
